# Generated by Django 5.0.3 on 2024-06-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('Xbox', 'Xbox'), ('Nintendo', 'Nintendo'), ('PlayStation', 'PlayStation')], default='Usado', max_length=50),
            preserve_default=False,
        ),
    ]
