# Generated by Django 5.0.3 on 2024-06-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_accessory_console'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='console',
            name='platform',
        ),
        migrations.AlterField(
            model_name='console',
            name='type',
            field=models.CharField(choices=[('Portátil', 'Portátil'), ('Hogar', 'Hogar')], max_length=50),
        ),
    ]
